---
title: "Visualizing Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualizing-data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
# knitr::opts_chunk$set(
#   collapse = TRUE,
#   comment = "#>"
# )
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  results = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  fig.width = 5,
  fig.height = 2.5,
  dpi = 300
)

```

```{r setup}
library(tidyplots)
```
# Amounts

# Distributions

```{r}

energy %>% 
  tidyplot(x = power) %>% 
  add_histogram()

energy %>% 
  tidyplot(x = power) %>% 
  add_density_curve()

energy %>% 
  tidyplot(x = power) %>% 
  add_density_histogram() %>% 
  add_density_curve()

# multiple distributions

energy %>% 
  tidyplot(x = energy_type, y = power, color = energy_type) %>% 
  add_violin()

energy %>% 
  tidyplot(x = energy_type, y = power, color = energy_type) %>% 
  add_jitter(jitter_width = 0.8, alpha = 0.3)

energy %>% 
  tidyplot(x = energy_type, y = power, color = energy_type) %>% 
  add_violin() %>% 
  add_jitter(jitter_width = 0.8, alpha = 0.3)

```


# Proportions

## Subproportions

## Megadrom

### Subsubheading

```{r}

# themes

p4 <- 
  energy %>% 
  tidyplot(year, power, color = energy_source) %>% 
  add_barstack_absolute()

p4
p4 %>% theme_minimal_y()
p4 %>% theme_ggplot2()

# proportions

energy %>% 
  tidyplot(year, power, color = energy_source) %>% 
  add_barstack_absolute()

energy %>% 
  tidyplot(year, power, color = energy_source) %>% 
  add_barstack_relative()

energy %>% 
  dplyr::filter(year %in% c(2005, 2010, 2015, 2020)) %>% 
  tidyplot(y = power, color = energy_source) %>% 
  add_pie() %>% 
  split_plot(by = year)

energy %>% 
  dplyr::filter(year %in% c(2005, 2010, 2015, 2020)) %>% 
  tidyplot(y = power, color = energy_source) %>% 
  add_donut() %>% 
  split_plot(by = year)

# pie and donut

animals %>% 
  tidyplot(y = weight, color = family) %>% 
  add_pie()

animals %>% 
  tidyplot(y = weight, color = family) %>% 
  add_donut()

animals %>% 
  tidyplot(color = family) %>% 
  add_pie()

animals %>% 
  tidyplot(color = family) %>% 
  add_donut()

# add_barstack_absolute

animals %>% 
  tidyplot(color = family) %>% 
  add_barstack_absolute()

animals %>% 
  tidyplot(x = diet, color = family) %>% 
  add_barstack_absolute()

## with y supplied

animals %>% 
  tidyplot(y = speed, color = family) %>% 
  add_barstack_absolute()

animals %>% 
  tidyplot(x = diet, y = speed, color = family) %>% 
  add_barstack_absolute()

# add_barstack_absolute

animals %>% 
  tidyplot(color = family) %>% 
  add_barstack_relative()

animals %>% 
  tidyplot(x = diet, color = family) %>% 
  add_barstack_relative()

animals %>% 
  tidyplot(x = diet, color = family) %>% 
  add_barstack_absolute(alpha = 0.3) %>% 
  add_areastack_absolute()

## with y supplied

animals %>% 
  tidyplot(x = diet, y = speed, color = family) %>% 
  add_barstack_absolute(alpha = 0.3) %>% 
  add_areastack_absolute()

animals %>% 
  tidyplot(y = speed, color = family) %>% 
  add_barstack_relative()

animals %>% 
  tidyplot(x = diet, y = speed, color = family) %>% 
  add_barstack_relative()

# curves

energy_week %>% 
  tidyplot(date, power, color = energy_source) %>% 
  add_line() %>% 
  remove_padding()

energy_week %>% 
  tidyplot(date, power, color = energy_source) %>% 
  add_area(alpha = 0.3)

energy_week %>% 
  tidyplot(date, power, color = energy_source) %>% 
  add_areastack_absolute()

energy_week %>% 
  tidyplot(date, power, color = energy_source) %>% 
  add_areastack_relative()

###

energy %>% 
  tidyplot(year, power, color = energy_type) %>% 
  add_barstack_absolute()

energy %>% 
  tidyplot(year, power, color = energy_type) %>% 
  add_barstack_relative()

new_colors <- c("Fossil" = "grey",
               "Nuclear" = "#F6C54D",
               "Renewable" = "#4FAE62",
               "Other" = "#C02D45")

energy %>% 
  dplyr::filter(year %in% c(2005, 2010, 2015, 2020)) %>% 
  tidyplot(y = power, color = energy_type) %>% 
  add_pie() %>% 
  adjust_colors(new_colors = new_colors) %>% 
  split_plot(by = year)

energy %>% 
  dplyr::filter(year %in% c(2005, 2010, 2015, 2020)) %>% 
  tidyplot(y = power, color = energy_type) %>% 
  add_donut() %>% 
  adjust_colors(new_colors = new_colors) %>%  
  split_plot(by = year)

energy %>% 
  dplyr::filter(year %in% c(2005, 2010, 2015, 2020)) %>% 
  tidyplot(x = year, y = power, color = energy_type) %>% 
  add_sum_line(dodge_width = 0) %>%
  add_sum_dot(dodge_width = 0) %>% 
  adjust_colors(new_colors = new_colors)

energy %>% 
  tidyplot(x = year, y = power, color = energy_type) %>% 
  add_areastack_absolute() %>% 
  adjust_colors(new_colors = new_colors)

energy %>% 
  tidyplot(x = year, y = power, color = energy_source) %>% 
  add_areastack_absolute()

energy %>% 
  dplyr::filter(year %in% c(2005, 2010, 2015, 2020)) %>% 
  tidyplot(x = year, y = power, color = energy_type) %>% 
  add_areastack_relative() %>% 
  adjust_colors(new_colors = new_colors)

energy_week %>% 
  tidyplot(date, power, color = energy_type) %>% 
  add_sum_line() %>%
  adjust_colors(new_colors = new_colors) %>% 
  remove_padding()

energy_week %>% 
  dplyr::summarise(power = sum(power), .by = c(date, energy_type)) %>% 
  tidyplot(date, power, color = energy_type) %>% 
  add_area(alpha = 0.3) %>% 
  adjust_colors(new_colors = new_colors)

energy_week %>% 
  tidyplot(date, power, color = energy_type) %>% 
  add_areastack_absolute() %>% 
  adjust_colors(new_colors = new_colors)

energy_week %>%
  tidyplot(date, power, color = energy_type) %>% 
  add_areastack_relative() %>% 
  adjust_colors(new_colors = new_colors)

```


# Uncertainty

```{r}
study %>% 
  tidyplot(x = treatment, y = score, color = treatment) %>% 
  add_mean_dash() %>% 
  add_ci95()

study %>% 
  tidyplot(x = treatment, y = score) %>% 
  add_ci95_ribbon() %>% 
  add_mean_line() %>% 
  add_jitter()

study %>% 
  tidyplot(x = treatment, y = score) %>% 
  add_ci95_ribbon() %>% 
  add_mean_line() %>% 
  add_jitter() %>% 
  adjust_colors("orange")

```


# x--y relationships

```{r}

energy_week %>% 
  tidyplot(date, power, color = energy_source) %>% 
  add_line() %>% 
  remove_padding()

energy_week %>% 
  tidyplot(date, power, color = energy_source) %>% 
  add_area(alpha = 0.3)

energy_week %>% 
  tidyplot(date, power, color = energy_source) %>% 
  add_points()

```

